spring.application.name=api-management-service
server.port=8081

info.app.name=API Management Service
info.app.description=Management Service for users, routes and gateway policies

spring.datasource.url=jdbc:mariadb://localhost:3306/gatekeeper
spring.datasource.username=gatekeeper
spring.datasource.password=gatekeeper123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true