spring.application.name=smart-gateway-service
spring.port=8080
info.app.name=Smart Gateway Service

info.app.description=Smart Gateway Service is a Spring Boot application that serves as a gateway for routing requests to various microservices. It provides features such as load balancing, security, and monitoring.